version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5
      - image: circleci/postgres:9.4.18-alpine
        environment:
          POSTGRES_USER: circleci
          POSTGRES_PASSWORD: super-secret
          POSTGRES_DB: monitor_api

    working_directory: ~/repo

    environment:
      DATABASE_URL: 'postgres://circleci:super-secret@localhost/monitor_api'
      NO_LOGS: 'true'

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            sudo apt-get install postgresql-client
            bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      - run:
          name: Waiting for Postgres to be ready
          command: |
            while ! psql $DATABASE_URL -c 'SELECT 1'; do
                echo 'Waiting for db'; sleep 3;
            done
      - run:
          name: run tests
          command: |
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)"

            bundle exec rspec --format progress \
                            --format RspecJunitFormatter \
                            --out /tmp/test-results/rspec.xml \
                            --format progress \
                            $TEST_FILES
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
